#!/bin/bash

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
skel_home=$script_dir/skel_home
for x in `ls -A $skel_home`
do
    cp -r $skel_home/$x ~/
done

# docker
# ref: https://docs.docker.com/engine/install/ubuntu/
sudo apt-get --yes install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
sudo apt-get update
sudo apt-get --yes install \
    docker-ce \
    docker-ce-cli \
    containerd.io 
# permissioning for docker
# ref: https://www.digitalocean.com/community/questions/how-to-fix-docker-got-permission-denied-while-trying-to-connect-to-the-docker-daemon-socket
sudo groupadd docker
sudo usermod -aG docker ${USER}

# misc essentials
sudo apt-get --yes install \
    vim \
    tree \
    tmux

# git
sudo apt-get install --yes git
git config --global credential.helper store
git config --global core.editor vim

# Other steps
cat << EOF
Other steps:
    * If necessary, install Mediatek wifi driver using *install_mediatek_driver* script
    * Install the latest versin of docker-compose (example instructions here: https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-compose-on-ubuntu-20-04)
    * Log out & back in before trying docker (eg: "docker ps")
EOF
